
name: Deploy infrastructure

description: 'Deploy infrastructure'

inputs:
  environment:
    description: 'The environment to deploy to'
    required: true
    default: 'qa'
  aws-account:
    description: 'The AWS account to deploy to'
    required: true
  aws-region:
    description: 'The AWS region to deploy to'
    required: true
  vars:
    description: 'The variables to pass to the CDK'
    required: true
  pr-number:
    description: 'The ticket number'
    required: false

outputs:
  folder:
    description: 'The folder to upload'
    value: ${{ steps.origin-path.outputs.value }}
  bucket:
    description: 'The bucket to upload to'
    value: ${{ steps.deploy.outputs.bucket }}
  id:
    description: 'The distribution id'
    value: ${{ steps.deploy.outputs.id }}
  url:
    description: 'The distribution url'
    value: ${{ steps.deploy.outputs.url }}


runs:
  using: composite

  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - name: Install and build cdk
      shell: bash
      working-directory: ./cdk
      run: |
        yarn install --frozen-lockfile
        yarn build
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/RG-Systems-GH-Actions
        role-session-name: vp-cdk-deploy
        aws-region: ${{ inputs.aws-region }}
    - id: origin-path
      shell: bash
      run: |
        ORIGIN_PATH=$(echo $GITHUB_SHA | cut -c 1-6)
        echo "value=$ORIGIN_PATH" >> $GITHUB_OUTPUT
    - id: project
      shell: bash
      run: |
        PROJECT_NAME=$(cat ./package.json | jq -r '.name')
        echo "value=$PROJECT_NAME" >> $GITHUB_OUTPUT
    - id: stack
      shell: bash
      run: |
        ENV=${{ inputs.environment }}
        STACK=${{ steps.project.outputs.value }}-$ENV
        if [ $ENV = "tmp" ]; then
          if [ -z "${{ inputs.pr-number }}" ]; then
            STACK=${{ steps.project.outputs.value }}-$ENV-${{ steps.origin-path.outputs.value }}
          else
            STACK=${{ steps.project.outputs.value }}-$ENV-${{ inputs.pr-number }}
          fi
        fi
        echo "value=$STACK" >> $GITHUB_OUTPUT
    - id: domain
      shell: bash
      run: |
        ENV=${{ inputs.environment }}
        DOMAIN=$(echo '${{ inputs.vars }}' | jq -r '.DOMAIN')
        if [ $ENV = "tmp" ]; then
          if [ -z "${{ inputs.pr-number }}" ]; then
            DOMAIN=$DOMAIN-${{ steps.origin-path.outputs.value }}
          else
            DOMAIN=$DOMAIN-${{ inputs.pr-number }}
          fi
        fi
        echo "value=$DOMAIN" >> $GITHUB_OUTPUT
    - shell: bash
      name: Create a .env file
      working-directory: ./cdk
      run: |
        touch .env
        echo '${{ inputs.vars }}' | jq -r 'to_entries | .[] | "VARIABLE_\(.key)=\(.value)"' >> .env
        echo "ENV=${{ inputs.environment }}" >> .env
        echo "STACK=${{ steps.stack.outputs.value }}" >> .env
        echo "DOMAIN=${{ steps.domain.outputs.value }}" >> .env
        echo "AWS_ACCOUNT=${{ inputs.aws-account }}" >> .env
        echo "AWS_REGION=${{ inputs.aws-region }}" >> .env
        echo "ORIGIN_PATH=${{ steps.origin-path.outputs.value }}" >> .env
        echo "PROJECT_NAME=${{ steps.project.outputs.value }}" >> .env
    - id: deploy
      shell: bash
      name: Deploy infrastructure
      working-directory: ./cdk
      run: |
        STACK=${{ steps.stack.outputs.value }}
        yarn cdk deploy $STACK --require-approval never --outputs-file cdk-outputs.json
        BUCKET=$(jq --arg key "$STACK" '.[$key].BucketName' cdk-outputs.json)
        echo "bucket=$(echo $BUCKET | sed -e 's/"//g')" >> $GITHUB_OUTPUT
        echo "id=$(jq --arg key "$STACK" '.[$key].DistributionId' cdk-outputs.json)" >> $GITHUB_OUTPUT
        URL=$(jq --arg key "$STACK" '.[$key].DeploymentUrl' cdk-outputs.json)
        echo "url=$(echo $URL | sed -e 's/"//g')" >> $GITHUB_OUTPUT
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cdk-outputs
        path: ./cdk/cdk-outputs.json
