name: Build the app

description: Build the app

runs:
  using: composite

  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'yarn'
    - name: Install and build app
      shell: bash
      run: |
        yarn install --frozen-lockfile
        yarn build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: application
        path: ./dist
