name: Deploy the app

description: Deploy the app

inputs:
  aws-account:
    description: 'The AWS account to deploy to'
    required: true
  aws-region:
    description: 'The AWS region to deploy to'
    required: true
  bucket:
    description: 'The bucket to upload to'
    required: true
  folder:
    description: 'The folder to upload'
    required: true
  id:
    description: 'The distribution id'
    required: true
  pr-number:
    description: 'The PR number'
    required: false

runs:
  using: composite

  steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: application
        path: ./dist
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/RG-Systems-GH-Actions
        role-session-name: vp-cdk-deploy
        aws-region: ${{ inputs.aws-region }}
    - name: Deploy to S3
      shell: bash
      run: |
        aws s3 sync ./dist s3://${{ inputs.bucket }}/${{ inputs.folder }}
        aws cloudfront create-invalidation --distribution-id ${{ inputs.id }} --paths "/*"
