name: Cherry-pick

on:
  pull_request:
    types:
      - closed

jobs:
  main:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'cherry-pick')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          BRANCHES=$(git branch --sort=-committerdate)
          echo ">>> BRANCHES: $BRANCHES"
          TARGET_BRANCH=$(echo $BRANCHES | head -n 1)
          echo ">>> TARGET_BRANCH: $TARGET_BRANCH"
          LABELS=${{ github.event.pull_request.labels.*.name }}
          echo ">>> LABELS: $LABELS"
          for LABEL in $LABELS; do
            echo ">>> LABEL: $LABEL"
            if [[ $LABEL == rc/* ]]; then
              TARGET_BRANCH=$LABEL
            fi
          done
          # echo ">>> TARGET_BRANCH: $TARGET_BRANCH"
          # VERSION=$(echo $TARGET_BRANCH | cut -d '/' -f 2)
          # echo ">>> VERSION: $VERSION"
          # git checkout $TARGET_BRANCH
          # git checkout -b "cp-$VERSION-${{ github.event.pull_request.head.sha }}"
          # git cherry-pick ${{ github.event.pull_request.head.sha }}
          # git push origin "cp-$VERSION-${{ github.event.pull_request.head.sha }}"
          # gh pr create --base $TARGET_BRANCH \
          #   --head "cp-$VERSION-${{ github.event.pull_request.head.sha }}" \
          #   --title "cherry-pick: ${{ github.event.pull_request.title }}" \
          #   --body "This PR was cherry-picked from #$PR_NUMBER"
