name: Deploy QA environment

on:
  push:
    branches:
      - main

jobs:
  infra:
    name: Deploy the infrastructure
    concurrency: cdk
    environment: qa
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - id: create-infra-template
        uses: RG-Systems/infra-action@main
        with:
          action: deploy
          name: vite-project
          environment: qa
          optimized: false
          domain: ${{ vars.STACK_DOMAIN }}
          variables: ${{ toJson(vars) }}
          aws-account: ${{ secrets.AWS_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-zone-id: Z03919341BL4WYM2KHJ2Q
          aws-origin-access-identity: E18FI623QZZ3OJ
      - run: |
          echo ">>> create-infra-template -> Check if in next step the file is available"
          ls -la
          echo "<<< create-infra-template -> Check if in next step the file is available"
