name: Deploy preview environment

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  infra:
    if: |
      (github.event.action == 'labeled' && github.event.label.name == 'preview') ||
      (github.event.action != 'labeled' && contains(github.event.pull_request.labels.*.name, 'preview'))

    name: Deploy the infrastructure
    concurrency: cdk
    environment: qa

    runs-on: ubuntu-latest

    outputs:
      folder: ${{ steps.deploy-infra.outputs.folder }}
      bucket: ${{ steps.deploy-infra.outputs.bucket }}
      id: ${{ steps.deploy-infra.outputs.id }}
      url: ${{ steps.deploy-infra.outputs.url }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - id: deploy-infra
        uses: RG-Systems/infra-action@main
        with:
          name: vite-project
          action: deploy
          variables: ${{ toJson(vars) }}
          aws-account: ${{ secrets.AWS_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}

  build:
    name: Build the application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-app

  deploy:
    name: Deploy the application
    concurrency: deploy
    environment: qa

    runs-on: ubuntu-latest

    needs:
      - infra
      - build

    permissions:
      deployments: write
      id-token: write
      contents: read

    steps:
      - name: create a github deployment
        uses: bobheadxi/deployments@v1.4.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.event.pull_request.number }}-tmp
          ref: ${{ github.head_ref }}
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-app
        with:
          aws-account: ${{ secrets.AWS_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}
          folder: ${{ needs.infra.outputs.folder }}
          bucket: ${{ needs.infra.outputs.bucket }}
          id: ${{ needs.infra.outputs.id }}
          pr-number: ${{ github.event.pull_request.number }}
      - name: update the github deployment status
        uses: bobheadxi/deployments@v1.4.0
        if: always()
        with:
          step: finish
          env: ${{ steps.deployment.outputs.env }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ needs.infra.outputs.url }}
