name: Deploy QA environment

on:
  push:
    branches:
      - main

jobs:
  infra:
    name: Deploy the infrastructure
    concurrency: cdk
    environment: qa
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - id: create-infra-template
        uses: RG-Systems/infra-action@main
        with:
          name: vite-project
          environment: qa
          variables: ${{ toJson(vars) }}
          aws-account: ${{ secrets.AWS_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          echo ">>> create-infra-template -> Check if in next step the file is available"
          ls -la
          echo "<<< create-infra-template -> Check if in next step the file is available"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT }}:role/RG-Systems-GH-Actions
          role-session-name: vp-cdk-deploy
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          echo ">>> aws -> Check if in next step the file is available"
          ls -la
          echo "<<< aws -> Check if in next step the file is available"
