name: Deploy PROD environment

on:
  release:
    types:
      - released

jobs:
  infra:
    name: Deploy the infrastructure
    concurrency: cdk
    environment: prod
    runs-on: ubuntu-latest

    outputs:
      folder: ${{ steps.deploy-infra.outputs.folder }}
      bucket: ${{ steps.deploy-infra.outputs.bucket }}
      id: ${{ steps.deploy-infra.outputs.id }}
      url: ${{ steps.deploy-infra.outputs.url }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - id: deploy-infra
        uses: RG-Systems/infra-action@main
        with:
          environment: prod
          action: deploy
          variables: ${{ toJson(vars) }}
          aws-account: ${{ secrets.AWS_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}

  build:
    name: Build the application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-app

  deploy:
    name: Deploy the application
    concurrency: deploy
    environment:
      name: prod
      url: ${{ needs.infra.outputs.url }}

    runs-on: ubuntu-latest

    needs:
      - infra
      - build

    permissions:
      deployments: write
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-app
        with:
          aws-account: ${{ secrets.AWS_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}
          folder: ${{ needs.infra.outputs.folder }}
          bucket: ${{ needs.infra.outputs.bucket }}
          id: ${{ needs.infra.outputs.id }}
