name: Destroy preview environment

on:
  pull_request:
    types: [unlabeled, closed]

jobs:
  configure:
    if: |
      (github.event.action == 'unlabeled' && github.event.label.name == 'preview') ||
      (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'preview'))

    outputs:
      env: ${{ steps.result.outputs.value }}

    name: Create the temporary environment
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - id: result
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ENV_NAME=${{ github.event.pull_request.number }}-tmp
          echo "value=$ENV_NAME" >> $GITHUB_OUTPUT
          echo "RESULT >>>"
          echo $ENV_NAME

  infra:
    name: Destroy the infrastructure
    concurrency: cdk
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.configure.outputs.env }}

    needs:
      - configure

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/destroy-infra
        with:
          environment: tmp
          aws-account: ${{ secrets.AWS_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}
          vars: ${{ toJson(vars) }}
          pr-number: ${{ github.event.pull_request.number }}

  remove:
    name: Remove the temporary environment
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.configure.outputs.env }}

    needs:
      - infra
      - configure

    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ENV_API=/repos/$GITHUB_REPOSITORY/environments
          ENV_NAME=${{ needs.configure.outputs.env }}
          gh api --method DELETE $ENV_API/$ENV_NAME
