name: Main

concurrency: main

on:
  push:
    branches:
      - main

jobs:
  infra:
    environment: qa
    runs-on: ubuntu-latest

    outputs:
      folder: ${{ steps.infra-deploy.outputs.folder }}
      bucket: ${{ steps.infra-deploy.outputs.bucket }}
      id: ${{ steps.infra-deploy.outputs.id }}
      url: ${{ steps.infra-deploy.outputs.url }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - id: infra-deploy
        uses: ./.github/actions/infra-deploy
        with:
          environment: qa

  build:
    environment: qa
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-app

  deploy:
    environment:
      name: qa
      url: ${{ needs.infra.outputs.url }}

    runs-on: ubuntu-latest

    needs:
      - infra
      - build

    permissions:
      deployments: write
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-app
        with:
          folder: ${{ needs.infra.outputs.folder }}
          bucket: ${{ needs.infra.outputs.bucket }}
          id: ${{ needs.infra.outputs.id }}
