name: Rollback

on:
  release

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "${{ github.event.action }}"
          echo "${{ github.event.release.body }}"
