name: Rollback

on:
  release:
    types:
      - created

jobs:
  main:
    name: DEBUG

    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "GITHUB: ${{ toJson(github) }}"
          echo "EVENT: ${{ github.event_name }}"
          echo "ACTION: ${{ github.event.action }}"
          echo "IS PRERELEASE: ${{ github.event.release.prerelease }}"
