name: Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: environment

jobs:
  main:
    name: DEBUG

    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echp "ENV: ${{ inputs.environment }}"
          echo "GITHUB: ${{ toJson(github) }}"
          echo "EVENT: ${{ github.event_name }}"
