name: Rollback

on:
  release:
    types:
      - edited
      - prereleased
      - released

jobs:
  main:
    name: DEBUG

    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "GITHUB: ${{ github }}"
          echo "EVENT: ${{ github.event_name }}"
          echo "ACTION: ${{ github.event.action }}"
          echo "CHANGES: ${{ github.event.changes.body }}"
          echo "RELEASE: ${{ github.event.release.body }}"
