name: Rollback

on:
  release:
    types:
      - created
      - deleted
      - edited
      - prereleased
      - published
      - released
      - unpublished

jobs:
  main:
    name: DEBUG

    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          echo "${{ github.event.action }}"
          echo "${{ github.event.release.body }}"
